### ISSUE TITLE
After modifying the chapter name, can't modify the link name of all the references to the changed chapter synchronously.

### ISSUE THREAD

**Issue by Cassiel-girl** [toshism/org-super-links#88]
After modifying the chapter name, you can't modify the link name of all the references to the changed chapter synchronously.

**Comment by toshism** [comment]
Yes, this is true. There is no central database that manages links. They are just org-mode links the same as any other, so they do not auto update. I definitely recommend using org-id for links though as documented here https://github.com/toshism/org-super-links?tab=readme-ov-file#org-id so that your links are never broken.
